# Projeto 3

### Gabriel Noal & William Palmieri

In [4]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [13]:
notas1 = pd.read_excel("Agriculture (p of GDP).xlsx")
notas1

                          País  Agriculture, value added (% of GDP)
0                     Abkhazia                                  NaN
1                  Afghanistan                            31.177550
2        Akrotiri and Dhekelia                                  NaN
3                      Albania                            20.401935
4                      Algeria                             6.915571
5               American Samoa                                  NaN
6                      Andorra                                  NaN
7                       Angola                            10.202085
8                     Anguilla                                  NaN
9          Antigua and Barbuda                             1.771181
10                   Argentina                             7.503740
11                     Armenia                            18.913892
12                       Aruba                                  NaN
13                   Australia                             2.365473
14                     Austria                             1.528136
15                  Azerbaijan                             6.648044
16                     Bahamas                             2.077301
17                     Bahrain                                  NaN
18                  Bangladesh                            18.728447
19                    Barbados                             3.027063
20                     Belarus                             9.434592
21                     Belgium                             0.671758
22                      Belize                                  NaN
23                       Benin                                  NaN
24                     Bermuda                             0.769960
25                      Bhutan                            18.748089
26                     Bolivia                            13.829343
27      Bosnia and Herzegovina                             7.838391
28                    Botswana                             2.952275
29                      Brazil                             5.626726
..                         ...                                  ...
240              United States                             1.103414
241                    Uruguay                             9.784916
242                       USSR                                  NaN
243                 Uzbekistan                            19.504980
244           Wallis et Futuna                                  NaN
245                    Vanuatu                            19.714399
246                  Venezuela                                  NaN
247         West Bank and Gaza                                  NaN
248               West Germany                                  NaN
249             Western Sahara                                  NaN
250                    Vietnam                            20.911004
251      Virgin Islands (U.S.)                                  NaN
252       North Yemen (former)                                  NaN
253       South Yemen (former)                                  NaN
254                      Yemen                             9.863141
255                 Yugoslavia                                  NaN
256                     Zambia                            21.553184
257                   Zimbabwe                            17.209262
258                      Åland                                  NaN
259                South Sudan                                  NaN
260                  Christian                                  NaN
261                  Coastline                                  NaN
262                    Curaçao                                  NaN
263  Sint Maarten (Dutch part)                                  NaN
264   St. Martin (French part)                                  NaN
265                 Antarctica                                  NaN
266    Virgin Islands, British                                  NaN
267        Hawaiian Trade Zone                                  NaN
268       U.S. Pacific Islands                                  NaN
269                Wake Island                                  NaN

[270 rows x 2 columns]

In [9]:
notas2 = pd.read_excel("indicator gapminder infant_mortality.xlsx")
notas2

                         País  Infant mortality rate
0                    Abkhazia                    NaN
1                 Afghanistan                   76.8
2       Akrotiri and Dhekelia                    NaN
3                     Albania                   15.4
4                     Algeria                   24.3
5              American Samoa                    NaN
6                     Andorra                    2.6
7                      Angola                  112.2
8                    Anguilla                    NaN
9         Antigua and Barbuda                    8.2
10                  Argentina                   13.4
11                    Armenia                   17.0
12                      Aruba                    NaN
13                  Australia                    4.2
14                    Austria                    3.7
15                 Azerbaijan                   35.5
16                    Bahamas                   11.7
17                    Bahrain                    7.6
18                 Bangladesh                   41.3
19                   Barbados                   13.9
20                    Belarus                    5.1
21                    Belgium                    3.7
22                     Belize                   16.7
23                      Benin                   72.3
24                    Bermuda                    NaN
25                     Bhutan                   36.1
26                    Bolivia                   38.4
27     Bosnia and Herzegovina                    6.7
28                   Botswana                   42.3
29                     Brazil                   15.4
..                        ...                    ...
230       Trinidad and Tobago                   21.6
231                   Tunisia                   15.7
232                    Turkey                   17.6
233              Turkmenistan                   51.7
234  Turks and Caicos Islands                    NaN
235                    Tuvalu                   27.0
236                    Uganda                   52.3
237                   Ukraine                   10.6
238      United Arab Emirates                    7.6
239            United Kingdom                    4.6
240             United States                    6.4
241                   Uruguay                   11.0
242                      USSR                    NaN
243                Uzbekistan                   40.8
244          Wallis et Futuna                    NaN
245                   Vanuatu                   23.8
246                 Venezuela                   14.5
247        West Bank and Gaza                   20.5
248              West Germany                    NaN
249            Western Sahara                    NaN
250                   Vietnam                   20.3
251     Virgin Islands (U.S.)                    NaN
252      North Yemen (former)                    NaN
253      South Yemen (former)                    NaN
254                     Yemen                   44.7
255                Yugoslavia                    NaN
256                    Zambia                   55.6
257                  Zimbabwe                   57.7
258                     Åland                    NaN
259               South Sudan                   73.1

[260 rows x 2 columns]

In [10]:
notas3 = pd.read_excel("indicator ti cpi 2009.xlsx")
notas3

                       Países  CPI
0                 New Zealand  9.3
1                     Denmark  9.3
2                      Sweden  9.2
3                   Singapore  9.3
4                 Switzerland  8.7
5                     Finland  9.2
6                 Netherlands  8.8
7                     Iceland  8.5
8                      Canada  8.9
9                   Australia  8.7
10                     Norway  8.6
11                 Luxembourg  8.5
12           Hong Kong, China  8.4
13                    Ireland  8.0
14                    Germany  7.9
15                    Austria  7.9
16             United Kingdom  7.6
17                      Japan  7.8
18              United States  7.1
19                   Barbados  7.8
20                    Belgium  7.1
21                Saint Lucia  NaN
22                      Qatar  7.7
23                     France  6.8
24                    Uruguay  6.9
25                      Chile  7.2
26                    Estonia  6.5
27                   Slovenia  6.4
28                     Cyprus  6.3
29       United Arab Emirates  6.3
..                        ...  ...
150                  Zimbabwe  2.4
151                  Cameroon  2.2
152                   Ecuador  2.5
153             Cote d'Ivoire  2.2
154                  Paraguay  2.2
155          Papua New Guinea  2.1
156                     Yemen  2.2
157  Central African Republic  2.1
158                Tajikistan  2.1
159                      Laos  2.1
160                  Cambodia  2.1
161             Guinea-Bissau  2.1
162                Kyrgyzstan  2.0
163                 Venezuela  2.0
164                    Angola  1.9
165               Congo, Rep.  2.1
166          Congo, Dem. Rep.  2.0
167              Turkmenistan  1.6
168                     Haiti  2.2
169         Equatorial Guinea  1.9
170                   Burundi  1.8
171                    Guinea  2.0
172                      Iran  2.2
173                Uzbekistan  1.6
174                      Chad  1.7
175                     Sudan  1.6
176                      Iraq  1.5
177                   Myanmar  1.4
178               Afghanistan  1.4
179                   Somalia  1.1

[180 rows x 2 columns]

In [11]:
notas4 = pd.read_excel("Indicator_HDI.xlsx")
notas4

                        Países    HDI
0                     Abkhazia    NaN
1                  Afghanistan  0.387
2        Akrotiri and Dhekelia    NaN
3                      Albania  0.734
4                      Algeria  0.691
5               American Samoa    NaN
6                      Andorra    NaN
7                       Angola  0.481
8                     Anguilla    NaN
9          Antigua and Barbuda    NaN
10                   Argentina  0.788
11                     Armenia  0.712
12                       Aruba    NaN
13                   Australia  0.926
14                     Austria  0.879
15                  Azerbaijan    NaN
16                     Bahamas  0.769
17                     Bahrain  0.805
18                  Bangladesh  0.491
19                    Barbados  0.790
20                     Belarus  0.746
21                     Belgium  0.883
22                      Belize  0.696
23                       Benin  0.422
24                     Bermuda    NaN
25                      Bhutan    NaN
26                     Bolivia  0.656
27      Bosnia and Herzegovina  0.730
28                    Botswana  0.626
29                      Brazil  0.708
..                         ...    ...
240              United States  0.906
241                    Uruguay  0.773
242                       USSR    NaN
243                 Uzbekistan  0.631
244           Wallis et Futuna    NaN
245                    Vanuatu    NaN
246                  Venezuela  0.732
247         West Bank and Gaza    NaN
248               West Germany    NaN
249             Western Sahara    NaN
250                    Vietnam  0.584
251      Virgin Islands (U.S.)    NaN
252       North Yemen (former)    NaN
253       South Yemen (former)    NaN
254                      Yemen  0.452
255                 Yugoslavia    NaN
256                     Zambia  0.419
257                   Zimbabwe  0.349
258                      Åland    NaN
259                South Sudan    NaN
260                  Christian    NaN
261                  Coastline    NaN
262                    Curaçao    NaN
263  Sint Maarten (Dutch part)    NaN
264   St. Martin (French part)    NaN
265                 Antarctica    NaN
266    Virgin Islands, British    NaN
267        Hawaiian Trade Zone    NaN
268       U.S. Pacific Islands    NaN
269                Wake Island    NaN

[270 rows x 2 columns]

In [12]:
notas5 = pd.read_excel("Service (p of GDP).xlsx")
notas5

                       Países  Services, etc., value added (% of GDP)
0                 Afghanistan                               47.607657
1                     Albania                               60.239255
2                     Algeria                               30.960967
3              American Samoa                                     NaN
4                     Andorra                                     NaN
5                      Angola                               30.751248
6         Antigua and Barbuda                               76.285758
7                   Argentina                               60.697484
8                     Armenia                               45.280450
9                       Aruba                                     NaN
10                  Australia                               76.374114
11                    Austria                               69.354040
12                 Azerbaijan                               32.268935
13                    Bahamas                               83.582767
14                    Bahrain                                     NaN
15                 Bangladesh                               52.614079
16                   Barbados                               73.762524
17                    Belarus                               48.290299
18                    Belgium                               77.691864
19                     Belize                                     NaN
20                      Benin                                     NaN
21                    Bermuda                               90.430645
22                     Bhutan                               38.080029
23                    Bolivia                               49.926150
24     Bosnia and Herzegovina                               63.902906
25                   Botswana                               56.648384
26                     Brazil                               68.500616
27                     Brunei                                     NaN
28                   Bulgaria                               63.820421
29               Burkina Faso                                     NaN
..                        ...                                     ...
183                    Sweden                               73.610393
184               Switzerland                               72.402695
185                     Syria                               46.470226
186                Tajikistan                               53.906890
187                  Tanzania                               46.928495
188                  Thailand                               45.197013
189               Timor-Leste                                     NaN
190                      Togo                                     NaN
191                     Tonga                               61.491066
192       Trinidad and Tobago                               46.320142
193                   Tunisia                               59.523938
194                    Turkey                               64.710523
195              Turkmenistan                               34.000000
196  Turks and Caicos Islands                                     NaN
197                    Tuvalu                                     NaN
198                    Uganda                               49.536234
199                   Ukraine                               62.127910
200      United Arab Emirates                               45.649246
201            United Kingdom                               78.070174
202             United States                               78.942646
203                   Uruguay                               65.335951
204                Uzbekistan                               47.300022
205                   Vanuatu                               70.403808
206                 Venezuela                                     NaN
207                   Vietnam                               38.849788
208     Virgin Islands (U.S.)                                     NaN
209        West Bank and Gaza                                     NaN
210               Yemen, Rep.                               52.438773
211                    Zambia                               44.345755
212                  Zimbabwe                               54.956285

[213 rows x 2 columns]